name: Check translations
on:
  push:
    branches:
      - master

jobs:
  test-translations:
    uses: biolab/orange-ci-cd/.github/workflows/test-translations.yml@master
    with:
      package-dir: Orange

  measure-energy:
    runs-on: ubuntu-latest
    needs: test-translations
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement

      - name: Record Final Measurement
        id: final-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
