name: Check translations
on:
  push:
    branches:
      - master

jobs:
  # 1️⃣ Run the reusable workflow directly
  test-translations:
    uses: biolab/orange-ci-cd/.github/workflows/test-translations.yml@master
    with:
      package-dir: Orange

  # 2️⃣ Surround it with energy measurement before and after
  measure-energy:
    runs-on: ubuntu-latest
    needs: test-translations
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement

      - name: Record Final Measurement
        id: final-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: get-measurement

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
